<?xml version="1.0" encoding="ISO-8859-1"?>
<point_set_file>
  <file_version>0.1</file_version>
  <point_set>
    <time_series>
      <time_series_id>0</time_series_id>
      <point>
        <id>0</id>
        <specification>0</specification>
        <x>18.9531</x>
        <y>-138.044</y>
        <z>-410.5</z>
      </point>
      <point>
        <id>1</id>
        <specification>0</specification>
        <x>29.1094</x>
        <y>-136.482</y>
        <z>-389.5</z>
      </point>
      <point>
        <id>2</id>
        <specification>0</specification>
        <x>35.3594</x>
        <y>-131.013</y>
        <z>-362.5</z>
      </point>
      <point>
        <id>3</id>
        <specification>0</specification>
        <x>35.3594</x>
        <y>-129.451</y>
        <z>-354.5</z>
      </point>
      <point>
        <id>4</id>
        <specification>0</specification>
        <x>26.7656</x>
        <y>-131.013</y>
        <z>-350.5</z>
      </point>
    </time_series>
  </point_set>
</point_set_file>
