<?xml version="1.0" encoding="ISO-8859-1"?>
<point_set_file>
  <file_version>0.1</file_version>
  <point_set>
    <time_series>
      <time_series_id>0</time_series_id>
      <point>
        <id>0</id>
        <specification>0</specification>
        <x>-19.7617</x>
        <y>-159.071</y>
        <z>-82</z>
      </point>
      <point>
        <id>1</id>
        <specification>0</specification>
        <x>-37.4258</x>
        <y>-142.336</y>
        <z>-117</z>
      </point>
      <point>
        <id>2</id>
        <specification>0</specification>
        <x>15.5664</x>
        <y>-141.407</y>
        <z>-99</z>
      </point>
      <point>
        <id>3</id>
        <specification>0</specification>
        <x>-49.5117</x>
        <y>-137.688</y>
        <z>-152</z>
      </point>
    </time_series>
  </point_set>
</point_set_file>
