<?xml version="1.0" encoding="ISO-8859-1"?>
<point_set_file>
  <file_version>0.1</file_version>
  <point_set>
    <time_series>
      <time_series_id>0</time_series_id>
      <point>
        <id>0</id>
        <specification>0</specification>
        <x>-0.742188</x>
        <y>127.539</y>
        <z>-97.1</z>
      </point>
      <point>
        <id>1</id>
        <specification>0</specification>
        <x>-0.742188</x>
        <y>130.469</y>
        <z>-107.1</z>
      </point>
      <point>
        <id>2</id>
        <specification>0</specification>
        <x>6.09375</x>
        <y>147.07</y>
        <z>-125.1</z>
      </point>
    </time_series>
  </point_set>
</point_set_file>
