<?xml version="1.0" encoding="ISO-8859-1"?>
<point_set_file>
  <file_version>0.1</file_version>
  <point_set>
    <time_series>
      <time_series_id>0</time_series_id>
      <point>
        <id>0</id>
        <specification>0</specification>
        <x>-66.8938</x>
        <y>-27.4219</y>
        <z>-571</z>
      </point>
      <point>
        <id>1</id>
        <specification>0</specification>
        <x>-53.5344</x>
        <y>-25.3125</y>
        <z>-627.25</z>
      </point>
      <point>
        <id>2</id>
        <specification>0</specification>
        <x>-66.1906</x>
        <y>-39.375</y>
        <z>-677.25</z>
      </point>
      <point>
        <id>3</id>
        <specification>0</specification>
        <x>-76.0344</x>
        <y>-51.3281</y>
        <z>-677.25</z>
      </point>
    </time_series>
  </point_set>
</point_set_file>
