<?xml version="1.0" encoding="ISO-8859-1"?>
<point_set_file>
  <file_version>0.1</file_version>
  <point_set>
    <time_series>
      <time_series_id>0</time_series_id>
      <point>
        <id>0</id>
        <specification>0</specification>
        <x>-6.33594</x>
        <y>172.719</y>
        <z>-163.75</z>
      </point>
      <point>
        <id>1</id>
        <specification>0</specification>
        <x>-2.35156</x>
        <y>183.344</y>
        <z>-173.75</z>
      </point>
    </time_series>
  </point_set>
</point_set_file>
