<?xml version="1.0" encoding="ISO-8859-1"?>
<point_set_file>
  <file_version>0.1</file_version>
  <point_set>
    <time_series>
      <time_series_id>0</time_series_id>
      <point>
        <id>0</id>
        <specification>0</specification>
        <x>-43.8281</x>
        <y>-16.3281</y>
        <z>-127.5</z>
      </point>
      <point>
        <id>1</id>
        <specification>0</specification>
        <x>-21.4844</x>
        <y>-1.71875</y>
        <z>-145</z>
      </point>
      <point>
        <id>2</id>
        <specification>0</specification>
        <x>-21.4844</x>
        <y>-4.29688</y>
        <z>-220</z>
      </point>
    </time_series>
  </point_set>
</point_set_file>
