<?xml version="1.0" encoding="ISO-8859-1"?>
<point_set_file>
  <file_version>0.1</file_version>
  <point_set>
    <time_series>
      <time_series_id>0</time_series_id>
      <point>
        <id>0</id>
        <specification>0</specification>
        <x>-1.09375</x>
        <y>-137.279</y>
        <z>44.9</z>
      </point>
      <point>
        <id>1</id>
        <specification>0</specification>
        <x>-47.9688</x>
        <y>-151.341</y>
        <z>-72.1</z>
      </point>
      <point>
        <id>2</id>
        <specification>0</specification>
        <x>-4.84375</x>
        <y>-139.154</y>
        <z>25.9</z>
      </point>
    </time_series>
  </point_set>
</point_set_file>
