<?xml version="1.0" encoding="ISO-8859-1"?>
<point_set_file>
  <file_version>0.1</file_version>
  <point_set>
    <time_series>
      <time_series_id>0</time_series_id>
      <point>
        <id>0</id>
        <specification>0</specification>
        <x>59.0987</x>
        <y>-201.677</y>
        <z>-596.423</z>
      </point>
      <point>
        <id>1</id>
        <specification>0</specification>
        <x>-56.1444</x>
        <y>-208.521</y>
        <z>-593.495</z>
      </point>
    </time_series>
  </point_set>
</point_set_file>
