<?xml version="1.0" encoding="ISO-8859-1"?>
<point_set_file>
  <file_version>0.1</file_version>
  <point_set>
    <time_series>
      <time_series_id>0</time_series_id>
      <point>
        <id>0</id>
        <specification>0</specification>
        <x>-22.5508</x>
        <y>-173.016</y>
        <z>-81</z>
      </point>
      <point>
        <id>1</id>
        <specification>0</specification>
        <x>-24.4102</x>
        <y>-159.071</y>
        <z>-87</z>
      </point>
      <point>
        <id>2</id>
        <specification>0</specification>
        <x>-26.2695</x>
        <y>-165.579</y>
        <z>-89</z>
      </point>
      <point>
        <id>3</id>
        <specification>0</specification>
        <x>13.707</x>
        <y>-130.25</y>
        <z>-93</z>
      </point>
      <point>
        <id>4</id>
        <specification>0</specification>
        <x>23.0039</x>
        <y>-131.18</y>
        <z>-105</z>
      </point>
      <point>
        <id>5</id>
        <specification>0</specification>
        <x>-36.4961</x>
        <y>-145.125</y>
        <z>-114</z>
      </point>
      <point>
        <id>6</id>
        <specification>0</specification>
        <x>-42.0742</x>
        <y>-139.547</y>
        <z>-116</z>
      </point>
      <point>
        <id>7</id>
        <specification>0</specification>
        <x>-34.6367</x>
        <y>-135.829</y>
        <z>-118</z>
      </point>
      <point>
        <id>8</id>
        <specification>0</specification>
        <x>-37.4258</x>
        <y>-149.774</y>
        <z>-119</z>
      </point>
      <point>
        <id>9</id>
        <specification>0</specification>
        <x>-44.8633</x>
        <y>-135.829</y>
        <z>-125</z>
      </point>
      <point>
        <id>10</id>
        <specification>0</specification>
        <x>-48.582</x>
        <y>-136.758</y>
        <z>-153</z>
      </point>
    </time_series>
  </point_set>
</point_set_file>
