<?xml version="1.0" encoding="ISO-8859-1"?>
<point_set_file>
  <file_version>0.1</file_version>
  <point_set>
    <time_series>
      <time_series_id>0</time_series_id>
      <point>
        <id>0</id>
        <specification>0</specification>
        <x>-8.16406</x>
        <y>170.742</y>
        <z>-311.1</z>
      </point>
      <point>
        <id>1</id>
        <specification>0</specification>
        <x>40.0781</x>
        <y>195.977</y>
        <z>-543.1</z>
      </point>
    </time_series>
  </point_set>
</point_set_file>
