<?xml version="1.0" encoding="ISO-8859-1"?>
<point_set_file>
  <file_version>0.1</file_version>
  <point_set>
    <time_series>
      <time_series_id>0</time_series_id>
      <point>
        <id>0</id>
        <specification>0</specification>
        <x>-17.666</x>
        <y>-126.574</y>
        <z>-316</z>
      </point>
      <point>
        <id>1</id>
        <specification>0</specification>
        <x>8.70898</x>
        <y>-150.476</y>
        <z>-300</z>
      </point>
      <point>
        <id>2</id>
        <specification>0</specification>
        <x>30.1387</x>
        <y>-134.816</y>
        <z>-280</z>
      </point>
    </time_series>
  </point_set>
</point_set_file>
