<?xml version="1.0" encoding="ISO-8859-1"?>
<point_set_file>
  <file_version>0.1</file_version>
  <point_set>
    <time_series>
      <time_series_id>0</time_series_id>
      <point>
        <id>0</id>
        <specification>0</specification>
        <x>-19.6133</x>
        <y>144.051</y>
        <z>-215.6</z>
      </point>
      <point>
        <id>1</id>
        <specification>0</specification>
        <x>-21.0586</x>
        <y>172.234</y>
        <z>-224.6</z>
      </point>
      <point>
        <id>2</id>
        <specification>0</specification>
        <x>-18.168</x>
        <y>166.453</y>
        <z>-232.6</z>
      </point>
      <point>
        <id>3</id>
        <specification>0</specification>
        <x>-27.5625</x>
        <y>162.117</y>
        <z>-246.6</z>
      </point>
    </time_series>
  </point_set>
</point_set_file>
