<?xml version="1.0" encoding="ISO-8859-1"?>
<point_set_file>
  <file_version>0.1</file_version>
  <point_set>
    <time_series>
      <time_series_id>0</time_series_id>
      <point>
        <id>0</id>
        <specification>0</specification>
        <x>-30.7686</x>
        <y>-25.1561</y>
        <z>-96</z>
      </point>
      <point>
        <id>1</id>
        <specification>0</specification>
        <x>-6.51082</x>
        <y>-7.18738</y>
        <z>-129</z>
      </point>
      <point>
        <id>2</id>
        <specification>0</specification>
        <x>-21.7843</x>
        <y>4.49231</y>
        <z>-162</z>
      </point>
    </time_series>
  </point_set>
</point_set_file>
