<?xml version="1.0" encoding="ISO-8859-1"?>
<point_set_file>
  <file_version>0.1</file_version>
  <point_set>
    <time_series>
      <time_series_id>0</time_series_id>
      <point>
        <id>0</id>
        <specification>0</specification>
        <x>20.7363</x>
        <y>-134.239</y>
        <z>-444</z>
      </point>
      <point>
        <id>1</id>
        <specification>0</specification>
        <x>14.0176</x>
        <y>-155.235</y>
        <z>-451</z>
      </point>
      <point>
        <id>2</id>
        <specification>0</specification>
        <x>57.6895</x>
        <y>-167.832</y>
        <z>-656</z>
      </point>
      <point>
        <id>3</id>
        <specification>0</specification>
        <x>54.3301</x>
        <y>-140.117</y>
        <z>-669</z>
      </point>
      <point>
        <id>4</id>
        <specification>0</specification>
        <x>19.0566</x>
        <y>-150.196</y>
        <z>-467</z>
      </point>
      <point>
        <id>5</id>
        <specification>0</specification>
        <x>17.377</x>
        <y>-145.996</y>
        <z>-482</z>
      </point>
      <point>
        <id>6</id>
        <specification>0</specification>
        <x>30.8145</x>
        <y>-126.68</y>
        <z>-599</z>
      </point>
      <point>
        <id>7</id>
        <specification>0</specification>
        <x>-67.4473</x>
        <y>-180.43</y>
        <z>-648</z>
      </point>
    </time_series>
  </point_set>
</point_set_file>
