<?xml version="1.0" encoding="ISO-8859-1"?>
<point_set_file>
  <file_version>0.1</file_version>
  <point_set>
    <time_series>
      <time_series_id>0</time_series_id>
      <point>
        <id>0</id>
        <specification>0</specification>
        <x>-37.1875</x>
        <y>143.898</y>
        <z>-125.1</z>
      </point>
      <point>
        <id>1</id>
        <specification>0</specification>
        <x>-33.2891</x>
        <y>128.305</y>
        <z>-125.1</z>
      </point>
      <point>
        <id>2</id>
        <specification>0</specification>
        <x>-36.2129</x>
        <y>147.797</y>
        <z>-135.1</z>
      </point>
      <point>
        <id>3</id>
        <specification>0</specification>
        <x>-58.6289</x>
        <y>153.645</y>
        <z>-161.1</z>
      </point>
    </time_series>
  </point_set>
</point_set_file>
