<?xml version="1.0" encoding="ISO-8859-1"?>
<point_set_file>
  <file_version>0.1</file_version>
  <point_set>
    <time_series>
      <time_series_id>0</time_series_id>
      <point>
        <id>0</id>
        <specification>0</specification>
        <x>12.5883</x>
        <y>-1.79073</y>
        <z>-379.914</z>
      </point>
      <point>
        <id>1</id>
        <specification>0</specification>
        <x>6.28919</x>
        <y>-8.98426</y>
        <z>-375</z>
      </point>
      <point>
        <id>2</id>
        <specification>0</specification>
        <x>13.4767</x>
        <y>1.797</y>
        <z>-367.5</z>
      </point>
    </time_series>
  </point_set>
</point_set_file>
