<?xml version="1.0" encoding="ISO-8859-1"?>
<point_set_file>
  <file_version>0.1</file_version>
  <point_set>
    <time_series>
      <time_series_id>0</time_series_id>
      <point>
        <id>0</id>
        <specification>0</specification>
        <x>-11.4805</x>
        <y>148.922</y>
        <z>-227.6</z>
      </point>
      <point>
        <id>1</id>
        <specification>0</specification>
        <x>-36.166</x>
        <y>134.709</y>
        <z>-209.6</z>
      </point>
    </time_series>
  </point_set>
</point_set_file>
