<?xml version="1.0" encoding="ISO-8859-1"?>
<point_set_file>
  <file_version>0.1</file_version>
  <point_set>
    <time_series>
      <time_series_id>0</time_series_id>
      <point>
        <id>0</id>
        <specification>0</specification>
        <x>-65.918</x>
        <y>-169.45</y>
        <z>-528.5</z>
      </point>
      <point>
        <id>1</id>
        <specification>0</specification>
        <x>-62.0117</x>
        <y>-189.958</y>
        <z>-547.5</z>
      </point>
      <point>
        <id>2</id>
        <specification>0</specification>
        <x>-75.6836</x>
        <y>-200.7</y>
        <z>-509.5</z>
      </point>
    </time_series>
  </point_set>
</point_set_file>
