<?xml version="1.0" encoding="ISO-8859-1"?>
<point_set_file>
  <file_version>0.1</file_version>
  <point_set>
    <time_series>
      <time_series_id>0</time_series_id>
      <point>
        <id>0</id>
        <specification>0</specification>
        <x>88.1836</x>
        <y>-130.045</y>
        <z>531.7</z>
      </point>
      <point>
        <id>1</id>
        <specification>0</specification>
        <x>101.309</x>
        <y>-141.53</y>
        <z>531.7</z>
      </point>
      <point>
        <id>2</id>
        <specification>0</specification>
        <x>14.3555</x>
        <y>-204.694</y>
        <z>391.7</z>
      </point>
      <point>
        <id>3</id>
        <specification>0</specification>
        <x>43.8867</x>
        <y>-129.225</y>
        <z>445.7</z>
      </point>
      <point>
        <id>4</id>
        <specification>0</specification>
        <x>34.043</x>
        <y>-121.842</y>
        <z>465.7</z>
      </point>
      <point>
        <id>5</id>
        <specification>0</specification>
        <x>14.3555</x>
        <y>-143.17</y>
        <z>531.7</z>
      </point>
    </time_series>
  </point_set>
</point_set_file>
