<?xml version="1.0" encoding="ISO-8859-1"?>
<point_set_file>
  <file_version>0.1</file_version>
  <point_set>
    <time_series>
      <time_series_id>0</time_series_id>
      <point>
        <id>0</id>
        <specification>0</specification>
        <x>-1.10352</x>
        <y>108.748</y>
        <z>-233.4</z>
      </point>
      <point>
        <id>1</id>
        <specification>0</specification>
        <x>73.6719</x>
        <y>111.109</y>
        <z>-179.4</z>
      </point>
      <point>
        <id>2</id>
        <specification>0</specification>
        <x>43.7617</x>
        <y>104.025</y>
        <z>-200.4</z>
      </point>
      <point>
        <id>3</id>
        <specification>0</specification>
        <x>44.5488</x>
        <y>148.104</y>
        <z>-148.4</z>
      </point>
      <point>
        <id>4</id>
        <specification>0</specification>
        <x>44.5488</x>
        <y>142.594</y>
        <z>-162.4</z>
      </point>
    </time_series>
  </point_set>
</point_set_file>
