<?xml version="1.0" encoding="ISO-8859-1"?>
<point_set_file>
  <file_version>0.1</file_version>
  <point_set>
    <time_series>
      <time_series_id>0</time_series_id>
      <point>
        <id>0</id>
        <specification>0</specification>
        <x>33.3262</x>
        <y>-98.437</y>
        <z>-223</z>
      </point>
      <point>
        <id>1</id>
        <specification>0</specification>
        <x>32.4082</x>
        <y>-98.437</y>
        <z>-226</z>
      </point>
      <point>
        <id>2</id>
        <specification>0</specification>
        <x>30.6383</x>
        <y>-98.4092</y>
        <z>-221.934</z>
      </point>
      <point>
        <id>3</id>
        <specification>0</specification>
        <x>29.6543</x>
        <y>-99.3549</y>
        <z>-226</z>
      </point>
      <point>
        <id>4</id>
        <specification>0</specification>
        <x>30.5723</x>
        <y>-99.3549</y>
        <z>-222</z>
      </point>
      <point>
        <id>5</id>
        <specification>0</specification>
        <x>29.6543</x>
        <y>-96.601</y>
        <z>-217</z>
      </point>
      <point>
        <id>6</id>
        <specification>0</specification>
        <x>30.5723</x>
        <y>-95.683</y>
        <z>-227</z>
      </point>
    </time_series>
  </point_set>
</point_set_file>
