<?xml version="1.0" encoding="ISO-8859-1"?>
<point_set_file>
  <file_version>0.1</file_version>
  <point_set>
    <time_series>
      <time_series_id>0</time_series_id>
      <point>
        <id>0</id>
        <specification>0</specification>
        <x>-9.27734</x>
        <y>-162.614</y>
        <z>-86.5</z>
      </point>
      <point>
        <id>1</id>
        <specification>0</specification>
        <x>-8.30078</x>
        <y>-148.942</y>
        <z>-87.5</z>
      </point>
      <point>
        <id>2</id>
        <specification>0</specification>
        <x>-1.46484</x>
        <y>-150.895</y>
        <z>-99.5</z>
      </point>
    </time_series>
  </point_set>
</point_set_file>
