<?xml version="1.0" encoding="ISO-8859-1"?>
<point_set_file>
  <file_version>0.1</file_version>
  <point_set>
    <time_series>
      <time_series_id>0</time_series_id>
      <point>
        <id>0</id>
        <specification>0</specification>
        <x>40.7813</x>
        <y>168.5</y>
        <z>-165.6</z>
      </point>
      <point>
        <id>1</id>
        <specification>0</specification>
        <x>47.0313</x>
        <y>170.844</y>
        <z>-170.6</z>
      </point>
      <point>
        <id>2</id>
        <specification>0</specification>
        <x>39.2188</x>
        <y>176.313</y>
        <z>-172.6</z>
      </point>
    </time_series>
  </point_set>
</point_set_file>
