<?xml version="1.0" encoding="ISO-8859-1"?>
<point_set_file>
  <file_version>0.1</file_version>
  <point_set>
    <time_series>
      <time_series_id>0</time_series_id>
      <point>
        <id>0</id>
        <specification>0</specification>
        <x>-12.9883</x>
        <y>165.898</y>
        <z>-16.3</z>
      </point>
      <point>
        <id>1</id>
        <specification>0</specification>
        <x>-19.1406</x>
        <y>166.582</y>
        <z>-22.3</z>
      </point>
      <point>
        <id>2</id>
        <specification>0</specification>
        <x>-21.875</x>
        <y>174.102</y>
        <z>-33.3</z>
      </point>
      <point>
        <id>3</id>
        <specification>0</specification>
        <x>36.9141</x>
        <y>140.605</y>
        <z>-41.3</z>
      </point>
    </time_series>
  </point_set>
</point_set_file>
