<?xml version="1.0" encoding="ISO-8859-1"?>
<point_set_file>
  <file_version>0.1</file_version>
  <point_set>
    <time_series>
      <time_series_id>0</time_series_id>
      <point>
        <id>0</id>
        <specification>0</specification>
        <x>-60.5781</x>
        <y>160.467</y>
        <z>-168.1</z>
      </point>
      <point>
        <id>1</id>
        <specification>0</specification>
        <x>-42.0605</x>
        <y>129.279</y>
        <z>-121.1</z>
      </point>
      <point>
        <id>2</id>
        <specification>0</specification>
        <x>-38.1621</x>
        <y>147.797</y>
        <z>-121.1</z>
      </point>
    </time_series>
  </point_set>
</point_set_file>
