<?xml version="1.0" encoding="ISO-8859-1"?>
<point_set_file>
  <file_version>0.1</file_version>
  <point_set>
    <time_series>
      <time_series_id>0</time_series_id>
      <point>
        <id>0</id>
        <specification>0</specification>
        <x>-55.0781</x>
        <y>-169.979</y>
        <z>-627</z>
      </point>
      <point>
        <id>1</id>
        <specification>0</specification>
        <x>-80.0781</x>
        <y>-198.104</y>
        <z>-634</z>
      </point>
      <point>
        <id>2</id>
        <specification>0</specification>
        <x>89.4531</x>
        <y>-191.073</y>
        <z>-618</z>
      </point>
      <point>
        <id>3</id>
        <specification>0</specification>
        <x>80.8594</x>
        <y>-192.636</y>
        <z>-618</z>
      </point>
      <point>
        <id>4</id>
        <specification>0</specification>
        <x>-72.2656</x>
        <y>-197.323</y>
        <z>-623</z>
      </point>
      <point>
        <id>5</id>
        <specification>0</specification>
        <x>-86.3281</x>
        <y>-201.229</y>
        <z>-617</z>
      </point>
    </time_series>
  </point_set>
</point_set_file>
