<?xml version="1.0" encoding="ISO-8859-1"?>
<point_set_file>
  <file_version>0.1</file_version>
  <point_set>
    <time_series>
      <time_series_id>0</time_series_id>
      <point>
        <id>0</id>
        <specification>0</specification>
        <x>16.1133</x>
        <y>-196.218</y>
        <z>-45</z>
      </point>
      <point>
        <id>1</id>
        <specification>0</specification>
        <x>37.5977</x>
        <y>-200.125</y>
        <z>-49</z>
      </point>
      <point>
        <id>2</id>
        <specification>0</specification>
        <x>-11.2305</x>
        <y>-232.351</y>
        <z>-68</z>
      </point>
      <point>
        <id>3</id>
        <specification>0</specification>
        <x>3.41797</x>
        <y>-126.882</y>
        <z>-105</z>
      </point>
      <point>
        <id>4</id>
        <specification>0</specification>
        <x>70.8008</x>
        <y>-135.671</y>
        <z>-132</z>
      </point>
      <point>
        <id>5</id>
        <specification>0</specification>
        <x>4.39453</x>
        <y>-114.187</y>
        <z>-159</z>
      </point>
      <point>
        <id>6</id>
        <specification>0</specification>
        <x>4.39453</x>
        <y>-114.187</y>
        <z>-182</z>
      </point>
    </time_series>
  </point_set>
</point_set_file>
