<?xml version="1.0" encoding="ISO-8859-1"?>
<point_set_file>
  <file_version>0.1</file_version>
  <point_set>
    <time_series>
      <time_series_id>0</time_series_id>
      <point>
        <id>0</id>
        <specification>0</specification>
        <x>24.9023</x>
        <y>-140.554</y>
        <z>-92</z>
      </point>
      <point>
        <id>1</id>
        <specification>0</specification>
        <x>30.7617</x>
        <y>-141.531</y>
        <z>-101</z>
      </point>
    </time_series>
  </point_set>
</point_set_file>
