<?xml version="1.0" encoding="ISO-8859-1"?>
<point_set_file>
  <file_version>0.1</file_version>
  <point_set>
    <time_series>
      <time_series_id>0</time_series_id>
      <point>
        <id>0</id>
        <specification>0</specification>
        <x>-63.6465</x>
        <y>-134.233</y>
        <z>-138</z>
      </point>
      <point>
        <id>1</id>
        <specification>0</specification>
        <x>-3.34961</x>
        <y>-125.366</y>
        <z>-107</z>
      </point>
      <point>
        <id>2</id>
        <specification>0</specification>
        <x>70.248</x>
        <y>-128.026</y>
        <z>-123</z>
      </point>
      <point>
        <id>3</id>
        <specification>0</specification>
        <x>66.7012</x>
        <y>-128.913</y>
        <z>-138</z>
      </point>
      <point>
        <id>4</id>
        <specification>0</specification>
        <x>-45.0254</x>
        <y>-151.081</y>
        <z>-107</z>
      </point>
      <point>
        <id>5</id>
        <specification>0</specification>
        <x>-42.3652</x>
        <y>-120.933</y>
        <z>-107</z>
      </point>
      <point>
        <id>6</id>
        <specification>0</specification>
        <x>21.4785</x>
        <y>-134.233</y>
        <z>-83</z>
      </point>
      <point>
        <id>7</id>
        <specification>0</specification>
        <x>58.7207</x>
        <y>-124.479</y>
        <z>-97</z>
      </point>
      <point>
        <id>8</id>
        <specification>0</specification>
        <x>35.666</x>
        <y>-120.933</y>
        <z>-97</z>
      </point>
      <point>
        <id>9</id>
        <specification>0</specification>
        <x>-4.23633</x>
        <y>-158.175</y>
        <z>-42</z>
      </point>
      <point>
        <id>10</id>
        <specification>0</specification>
        <x>-12.2168</x>
        <y>-144.874</y>
        <z>-83</z>
      </point>
    </time_series>
  </point_set>
</point_set_file>
