<?xml version="1.0" encoding="ISO-8859-1"?>
<point_set_file>
  <file_version>0.1</file_version>
  <point_set>
    <time_series>
      <time_series_id>0</time_series_id>
      <point>
        <id>0</id>
        <specification>0</specification>
        <x>-14.0625</x>
        <y>-12.6563</y>
        <z>-143.75</z>
      </point>
      <point>
        <id>1</id>
        <specification>0</specification>
        <x>-21.0938</x>
        <y>-2.8125</y>
        <z>-112.5</z>
      </point>
      <point>
        <id>2</id>
        <specification>0</specification>
        <x>-18.9844</x>
        <y>-4.92188</y>
        <z>-165</z>
      </point>
      <point>
        <id>3</id>
        <specification>0</specification>
        <x>-21.7969</x>
        <y>7.03125</y>
        <z>-143.75</z>
      </point>
      <point>
        <id>4</id>
        <specification>0</specification>
        <x>12.6563</x>
        <y>-28.8281</y>
        <z>-118.75</z>
      </point>
    </time_series>
  </point_set>
</point_set_file>
