<?xml version="1.0" encoding="ISO-8859-1"?>
<point_set_file>
  <file_version>0.1</file_version>
  <point_set>
    <time_series>
      <time_series_id>0</time_series_id>
      <point>
        <id>0</id>
        <specification>0</specification>
        <x>26.7988</x>
        <y>-122.956</y>
        <z>-635.5</z>
      </point>
      <point>
        <id>1</id>
        <specification>0</specification>
        <x>28.4373</x>
        <y>-123.73</y>
        <z>-638.428</z>
      </point>
    </time_series>
  </point_set>
</point_set_file>
