# CMake generated Testfile for 
# Source directory: /home/rothhr/Code/CADLab-GitHub/CADLab-git/LymphNodeRFCNNPipeline/nifty_reg-1.3.9/nifty_reg/reg-test
# Build directory: /home/rothhr/Code/CADLab-GitHub/CADLab-git/LymphNodeRFCNNPipeline/nifty_reg-1.3.9_linux_x64r/reg-test
# 
# This file includes the relevant testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
ADD_TEST(interpolation_3D_NN "reg_test_interp" "/home/rothhr/Code/CADLab-GitHub/CADLab-git/LymphNodeRFCNNPipeline/nifty_reg-1.3.9/nifty_reg/reg-test/reg-test-data/brainweb_3D.nii.gz" "/home/rothhr/Code/CADLab-GitHub/CADLab-git/LymphNodeRFCNNPipeline/nifty_reg-1.3.9/nifty_reg/reg-test/reg-test-data/test_DEF_BW_3D.nii.gz" "0" "/home/rothhr/Code/CADLab-GitHub/CADLab-git/LymphNodeRFCNNPipeline/nifty_reg-1.3.9/nifty_reg/reg-test/reg-test-data/test_warped_BW_3D_NN.nii.gz")
ADD_TEST(interpolation_3D_LIN "reg_test_interp" "/home/rothhr/Code/CADLab-GitHub/CADLab-git/LymphNodeRFCNNPipeline/nifty_reg-1.3.9/nifty_reg/reg-test/reg-test-data/brainweb_3D.nii.gz" "/home/rothhr/Code/CADLab-GitHub/CADLab-git/LymphNodeRFCNNPipeline/nifty_reg-1.3.9/nifty_reg/reg-test/reg-test-data/test_DEF_BW_3D.nii.gz" "1" "/home/rothhr/Code/CADLab-GitHub/CADLab-git/LymphNodeRFCNNPipeline/nifty_reg-1.3.9/nifty_reg/reg-test/reg-test-data/test_warped_BW_3D_LIN.nii.gz")
ADD_TEST(interpolation_3D_SPL "reg_test_interp" "/home/rothhr/Code/CADLab-GitHub/CADLab-git/LymphNodeRFCNNPipeline/nifty_reg-1.3.9/nifty_reg/reg-test/reg-test-data/brainweb_3D.nii.gz" "/home/rothhr/Code/CADLab-GitHub/CADLab-git/LymphNodeRFCNNPipeline/nifty_reg-1.3.9/nifty_reg/reg-test/reg-test-data/test_DEF_BW_3D.nii.gz" "3" "/home/rothhr/Code/CADLab-GitHub/CADLab-git/LymphNodeRFCNNPipeline/nifty_reg-1.3.9/nifty_reg/reg-test/reg-test-data/test_warped_BW_3D_SPL.nii.gz")
ADD_TEST(interpolation_2D_NN "reg_test_interp" "/home/rothhr/Code/CADLab-GitHub/CADLab-git/LymphNodeRFCNNPipeline/nifty_reg-1.3.9/nifty_reg/reg-test/reg-test-data/brainweb_2D.nii.gz" "/home/rothhr/Code/CADLab-GitHub/CADLab-git/LymphNodeRFCNNPipeline/nifty_reg-1.3.9/nifty_reg/reg-test/reg-test-data/test_DEF_BW_2D.nii.gz" "0" "/home/rothhr/Code/CADLab-GitHub/CADLab-git/LymphNodeRFCNNPipeline/nifty_reg-1.3.9/nifty_reg/reg-test/reg-test-data/test_warped_BW_2D_NN.nii.gz")
ADD_TEST(interpolation_2D_LIN "reg_test_interp" "/home/rothhr/Code/CADLab-GitHub/CADLab-git/LymphNodeRFCNNPipeline/nifty_reg-1.3.9/nifty_reg/reg-test/reg-test-data/brainweb_2D.nii.gz" "/home/rothhr/Code/CADLab-GitHub/CADLab-git/LymphNodeRFCNNPipeline/nifty_reg-1.3.9/nifty_reg/reg-test/reg-test-data/test_DEF_BW_2D.nii.gz" "1" "/home/rothhr/Code/CADLab-GitHub/CADLab-git/LymphNodeRFCNNPipeline/nifty_reg-1.3.9/nifty_reg/reg-test/reg-test-data/test_warped_BW_2D_LIN.nii.gz")
ADD_TEST(interpolation_2D_SPL "reg_test_interp" "/home/rothhr/Code/CADLab-GitHub/CADLab-git/LymphNodeRFCNNPipeline/nifty_reg-1.3.9/nifty_reg/reg-test/reg-test-data/brainweb_2D.nii.gz" "/home/rothhr/Code/CADLab-GitHub/CADLab-git/LymphNodeRFCNNPipeline/nifty_reg-1.3.9/nifty_reg/reg-test/reg-test-data/test_DEF_BW_2D.nii.gz" "3" "/home/rothhr/Code/CADLab-GitHub/CADLab-git/LymphNodeRFCNNPipeline/nifty_reg-1.3.9/nifty_reg/reg-test/reg-test-data/test_warped_BW_2D_SPL.nii.gz")
ADD_TEST(mat44_operations "reg_test_mat44_operations")
