<?xml version="1.0" encoding="ISO-8859-1"?>
<point_set_file>
  <file_version>0.1</file_version>
  <point_set>
    <time_series>
      <time_series_id>0</time_series_id>
      <point>
        <id>0</id>
        <specification>0</specification>
        <x>19.1484</x>
        <y>149.32</y>
        <z>-424.4</z>
      </point>
      <point>
        <id>1</id>
        <specification>0</specification>
        <x>-2.15085</x>
        <y>160.406</y>
        <z>-473.367</z>
      </point>
      <point>
        <id>2</id>
        <specification>0</specification>
        <x>22.345</x>
        <y>150.912</y>
        <z>-423.354</z>
      </point>
    </time_series>
  </point_set>
</point_set_file>
