<?xml version="1.0" encoding="ISO-8859-1"?>
<point_set_file>
  <file_version>0.1</file_version>
  <point_set>
    <time_series>
      <time_series_id>0</time_series_id>
      <point>
        <id>0</id>
        <specification>0</specification>
        <x>7.16992</x>
        <y>-108.824</y>
        <z>-369.5</z>
      </point>
      <point>
        <id>1</id>
        <specification>0</specification>
        <x>22.0879</x>
        <y>-111.964</y>
        <z>-410.5</z>
      </point>
      <point>
        <id>2</id>
        <specification>0</specification>
        <x>-0.681641</x>
        <y>-228.953</y>
        <z>-468.5</z>
      </point>
    </time_series>
  </point_set>
</point_set_file>
