<?xml version="1.0" encoding="ISO-8859-1"?>
<point_set_file>
  <file_version>0.1</file_version>
  <point_set>
    <time_series>
      <time_series_id>0</time_series_id>
      <point>
        <id>0</id>
        <specification>0</specification>
        <x>-39.5313</x>
        <y>-148.421</y>
        <z>-223</z>
      </point>
      <point>
        <id>1</id>
        <specification>0</specification>
        <x>-17.9688</x>
        <y>-177.484</y>
        <z>-290</z>
      </point>
      <point>
        <id>2</id>
        <specification>0</specification>
        <x>22.3438</x>
        <y>-171.859</y>
        <z>-246</z>
      </point>
      <point>
        <id>3</id>
        <specification>0</specification>
        <x>-13.2813</x>
        <y>-176.546</y>
        <z>-275</z>
      </point>
    </time_series>
  </point_set>
</point_set_file>
