<?xml version="1.0" encoding="ISO-8859-1"?>
<point_set_file>
  <file_version>0.1</file_version>
  <point_set>
    <time_series>
      <time_series_id>0</time_series_id>
      <point>
        <id>0</id>
        <specification>0</specification>
        <x>13.8242</x>
        <y>192.117</y>
        <z>-407.9</z>
      </point>
      <point>
        <id>1</id>
        <specification>0</specification>
        <x>-12.1523</x>
        <y>176.395</y>
        <z>-435.9</z>
      </point>
      <point>
        <id>2</id>
        <specification>0</specification>
        <x>6.98828</x>
        <y>149.051</y>
        <z>-395.9</z>
      </point>
      <point>
        <id>3</id>
        <specification>0</specification>
        <x>11.7734</x>
        <y>190.066</y>
        <z>-441.9</z>
      </point>
    </time_series>
  </point_set>
</point_set_file>
