<?xml version="1.0" encoding="ISO-8859-1"?>
<point_set_file>
  <file_version>0.1</file_version>
  <point_set>
    <time_series>
      <time_series_id>0</time_series_id>
      <point>
        <id>0</id>
        <specification>0</specification>
        <x>-36.166</x>
        <y>134.709</y>
        <z>-206.6</z>
      </point>
      <point>
        <id>1</id>
        <specification>0</specification>
        <x>-6.24414</x>
        <y>150.418</y>
        <z>-217.6</z>
      </point>
      <point>
        <id>2</id>
        <specification>0</specification>
        <x>-21.9531</x>
        <y>142.189</y>
        <z>-234.6</z>
      </point>
    </time_series>
  </point_set>
</point_set_file>
