<?xml version="1.0" encoding="ISO-8859-1"?>
<point_set_file>
  <file_version>0.1</file_version>
  <point_set>
    <time_series>
      <time_series_id>0</time_series_id>
      <point>
        <id>0</id>
        <specification>0</specification>
        <x>-14.3271</x>
        <y>-126.73</y>
        <z>-218.1</z>
      </point>
      <point>
        <id>1</id>
        <specification>0</specification>
        <x>-44.9639</x>
        <y>-140.051</y>
        <z>-224.1</z>
      </point>
    </time_series>
  </point_set>
</point_set_file>
