<?xml version="1.0" encoding="ISO-8859-1"?>
<point_set_file>
  <file_version>0.1</file_version>
  <point_set>
    <time_series>
      <time_series_id>0</time_series_id>
      <point>
        <id>0</id>
        <specification>0</specification>
        <x>-11.0938</x>
        <y>130.703</y>
        <z>26.8</z>
      </point>
      <point>
        <id>1</id>
        <specification>0</specification>
        <x>-0.03125</x>
        <y>132.547</y>
        <z>23.8</z>
      </point>
      <point>
        <id>2</id>
        <specification>0</specification>
        <x>-2.79688</x>
        <y>127.016</y>
        <z>22.8</z>
      </point>
    </time_series>
  </point_set>
</point_set_file>
