<?xml version="1.0" encoding="ISO-8859-1"?>
<point_set_file>
  <file_version>0.1</file_version>
  <point_set>
    <time_series>
      <time_series_id>0</time_series_id>
      <point>
        <id>0</id>
        <specification>0</specification>
        <x>-6.65625</x>
        <y>142.363</y>
        <z>136.9</z>
      </point>
      <point>
        <id>1</id>
        <specification>0</specification>
        <x>-12.6309</x>
        <y>141.51</y>
        <z>120.9</z>
      </point>
      <point>
        <id>2</id>
        <specification>0</specification>
        <x>-39.9434</x>
        <y>151.752</y>
        <z>84.9</z>
      </point>
    </time_series>
  </point_set>
</point_set_file>
