<?xml version="1.0" encoding="ISO-8859-1"?>
<point_set_file>
  <file_version>0.1</file_version>
  <point_set>
    <time_series>
      <time_series_id>0</time_series_id>
      <point>
        <id>0</id>
        <specification>0</specification>
        <x>-6.28894</x>
        <y>-1.79675</y>
        <z>-103.75</z>
      </point>
      <point>
        <id>1</id>
        <specification>0</specification>
        <x>-17.0702</x>
        <y>17.9689</y>
        <z>-136.25</z>
      </point>
    </time_series>
  </point_set>
</point_set_file>
