<?xml version="1.0" encoding="ISO-8859-1"?>
<point_set_file>
  <file_version>0.1</file_version>
  <point_set>
    <time_series>
      <time_series_id>0</time_series_id>
      <point>
        <id>0</id>
        <specification>0</specification>
        <x>62.4023</x>
        <y>66.9609</y>
        <z>201.5</z>
      </point>
      <point>
        <id>1</id>
        <specification>0</specification>
        <x>-81.7383</x>
        <y>67.8398</y>
        <z>201.5</z>
      </point>
      <point>
        <id>2</id>
        <specification>0</specification>
        <x>-24.6094</x>
        <y>101.238</y>
        <z>535.5</z>
      </point>
    </time_series>
  </point_set>
</point_set_file>
