<?xml version="1.0" encoding="ISO-8859-1"?>
<point_set_file>
  <file_version>0.1</file_version>
  <point_set>
    <time_series>
      <time_series_id>0</time_series_id>
      <point>
        <id>0</id>
        <specification>0</specification>
        <x>0.234375</x>
        <y>129.492</y>
        <z>-101.1</z>
      </point>
      <point>
        <id>1</id>
        <specification>0</specification>
        <x>1.21094</x>
        <y>134.375</y>
        <z>-107.1</z>
      </point>
      <point>
        <id>2</id>
        <specification>0</specification>
        <x>7.07031</x>
        <y>148.047</y>
        <z>-128.1</z>
      </point>
    </time_series>
  </point_set>
</point_set_file>
