<?xml version="1.0" encoding="ISO-8859-1"?>
<point_set_file>
  <file_version>0.1</file_version>
  <point_set>
    <time_series>
      <time_series_id>0</time_series_id>
      <point>
        <id>0</id>
        <specification>0</specification>
        <x>-1.48438</x>
        <y>173.711</y>
        <z>-315.1</z>
      </point>
      <point>
        <id>1</id>
        <specification>0</specification>
        <x>40.1712</x>
        <y>195.983</y>
        <z>-543.015</z>
      </point>
      <point>
        <id>2</id>
        <specification>0</specification>
        <x>-8.07361</x>
        <y>170.801</y>
        <z>-311.012</z>
      </point>
    </time_series>
  </point_set>
</point_set_file>
