<?xml version="1.0" encoding="ISO-8859-1"?>
<point_set_file>
  <file_version>0.1</file_version>
  <point_set>
    <time_series>
      <time_series_id>0</time_series_id>
      <point>
        <id>0</id>
        <specification>0</specification>
        <x>-10.004</x>
        <y>-34.629</y>
        <z>-151.25</z>
      </point>
      <point>
        <id>1</id>
        <specification>0</specification>
        <x>-6.92584</x>
        <y>-7.69537</y>
        <z>-182.5</z>
      </point>
      <point>
        <id>2</id>
        <specification>0</specification>
        <x>-36.9375</x>
        <y>-28.4727</y>
        <z>-176.25</z>
      </point>
    </time_series>
  </point_set>
</point_set_file>
