<?xml version="1.0" encoding="ISO-8859-1"?>
<point_set_file>
  <file_version>0.1</file_version>
  <point_set>
    <time_series>
      <time_series_id>0</time_series_id>
      <point>
        <id>0</id>
        <specification>0</specification>
        <x>17.0508</x>
        <y>168.141</y>
        <z>-158.4</z>
      </point>
      <point>
        <id>1</id>
        <specification>0</specification>
        <x>25.9375</x>
        <y>177.711</y>
        <z>-169.4</z>
      </point>
    </time_series>
  </point_set>
</point_set_file>
