<?xml version="1.0" encoding="ISO-8859-1"?>
<point_set_file>
  <file_version>0.1</file_version>
  <point_set>
    <time_series>
      <time_series_id>0</time_series_id>
      <point>
        <id>0</id>
        <specification>0</specification>
        <x>24.665</x>
        <y>-191.873</y>
        <z>-307.2</z>
      </point>
      <point>
        <id>1</id>
        <specification>0</specification>
        <x>24.665</x>
        <y>-155.283</y>
        <z>-293.2</z>
      </point>
      <point>
        <id>2</id>
        <specification>0</specification>
        <x>29.4795</x>
        <y>-191.873</y>
        <z>-299.2</z>
      </point>
      <point>
        <id>3</id>
        <specification>0</specification>
        <x>-16.7393</x>
        <y>-140.84</y>
        <z>-204.2</z>
      </point>
      <point>
        <id>4</id>
        <specification>0</specification>
        <x>18.8877</x>
        <y>-157.209</y>
        <z>-262.2</z>
      </point>
      <point>
        <id>5</id>
        <specification>0</specification>
        <x>15.999</x>
        <y>-153.357</y>
        <z>-327.2</z>
      </point>
      <point>
        <id>6</id>
        <specification>0</specification>
        <x>25.6279</x>
        <y>-148.543</y>
        <z>-336.2</z>
      </point>
    </time_series>
  </point_set>
</point_set_file>
