<?xml version="1.0" encoding="ISO-8859-1"?>
<point_set_file>
  <file_version>0.1</file_version>
  <point_set>
    <time_series>
      <time_series_id>0</time_series_id>
      <point>
        <id>0</id>
        <specification>0</specification>
        <x>-10</x>
        <y>170.094</y>
        <z>-77.9</z>
      </point>
      <point>
        <id>1</id>
        <specification>0</specification>
        <x>-7.0625</x>
        <y>160.547</y>
        <z>-35.4</z>
      </point>
    </time_series>
  </point_set>
</point_set_file>
