<?xml version="1.0" encoding="ISO-8859-1"?>
<point_set_file>
  <file_version>0.1</file_version>
  <point_set>
    <time_series>
      <time_series_id>0</time_series_id>
      <point>
        <id>0</id>
        <specification>0</specification>
        <x>23.0064</x>
        <y>-190.404</y>
        <z>719.023</z>
      </point>
      <point>
        <id>1</id>
        <specification>0</specification>
        <x>42.6885</x>
        <y>-169.83</y>
        <z>677.003</z>
      </point>
    </time_series>
  </point_set>
</point_set_file>
