<?xml version="1.0" encoding="ISO-8859-1"?>
<point_set_file>
  <file_version>0.1</file_version>
  <point_set>
    <time_series>
      <time_series_id>0</time_series_id>
      <point>
        <id>0</id>
        <specification>0</specification>
        <x>-19.6602</x>
        <y>168.887</y>
        <z>-111.55</z>
      </point>
      <point>
        <id>1</id>
        <specification>0</specification>
        <x>-5.30469</x>
        <y>170.254</y>
        <z>-135.3</z>
      </point>
      <point>
        <id>2</id>
        <specification>0</specification>
        <x>0.847656</x>
        <y>172.988</y>
        <z>-146.55</z>
      </point>
      <point>
        <id>3</id>
        <specification>0</specification>
        <x>7</x>
        <y>160.684</y>
        <z>-187.8</z>
      </point>
    </time_series>
  </point_set>
</point_set_file>
