<?xml version="1.0" encoding="ISO-8859-1"?>
<point_set_file>
  <file_version>0.1</file_version>
  <point_set>
    <time_series>
      <time_series_id>0</time_series_id>
      <point>
        <id>0</id>
        <specification>0</specification>
        <x>19.875</x>
        <y>165.406</y>
        <z>-624.8</z>
      </point>
      <point>
        <id>1</id>
        <specification>0</specification>
        <x>26.7466</x>
        <y>168.85</y>
        <z>-611.787</z>
      </point>
      <point>
        <id>2</id>
        <specification>0</specification>
        <x>19.9025</x>
        <y>164.113</y>
        <z>-622.72</z>
      </point>
      <point>
        <id>3</id>
        <specification>0</specification>
        <x>26.7109</x>
        <y>171.559</y>
        <z>-614.8</z>
      </point>
    </time_series>
  </point_set>
</point_set_file>
