<?xml version="1.0" encoding="ISO-8859-1"?>
<point_set_file>
  <file_version>0.1</file_version>
  <point_set>
    <time_series>
      <time_series_id>0</time_series_id>
      <point>
        <id>0</id>
        <specification>0</specification>
        <x>-1.17188</x>
        <y>-121.666</y>
        <z>-342</z>
      </point>
      <point>
        <id>1</id>
        <specification>0</specification>
        <x>33.9844</x>
        <y>-106.041</y>
        <z>-272</z>
      </point>
    </time_series>
  </point_set>
</point_set_file>
