<?xml version="1.0" encoding="ISO-8859-1"?>
<point_set_file>
  <file_version>0.1</file_version>
  <point_set>
    <time_series>
      <time_series_id>0</time_series_id>
      <point>
        <id>0</id>
        <specification>0</specification>
        <x>-18.457</x>
        <y>167.949</y>
        <z>-27.3</z>
      </point>
      <point>
        <id>1</id>
        <specification>0</specification>
        <x>37.5977</x>
        <y>141.973</y>
        <z>-42.3</z>
      </point>
    </time_series>
  </point_set>
</point_set_file>
