<?xml version="1.0" encoding="ISO-8859-1"?>
<point_set_file>
  <file_version>0.1</file_version>
  <point_set>
    <time_series>
      <time_series_id>0</time_series_id>
      <point>
        <id>0</id>
        <specification>0</specification>
        <x>37.4277</x>
        <y>-157.267</y>
        <z>-508</z>
      </point>
      <point>
        <id>1</id>
        <specification>0</specification>
        <x>41.4316</x>
        <y>-156.466</y>
        <z>-520</z>
      </point>
      <point>
        <id>2</id>
        <specification>0</specification>
        <x>38.2285</x>
        <y>-164.474</y>
        <z>-521</z>
      </point>
      <point>
        <id>3</id>
        <specification>0</specification>
        <x>-1.81055</x>
        <y>-160.47</y>
        <z>-522</z>
      </point>
      <point>
        <id>4</id>
        <specification>0</specification>
        <x>-5.01367</x>
        <y>-179.689</y>
        <z>-523</z>
      </point>
      <point>
        <id>5</id>
        <specification>0</specification>
        <x>5.39648</x>
        <y>-173.283</y>
        <z>-524</z>
      </point>
      <point>
        <id>6</id>
        <specification>0</specification>
        <x>-6.61523</x>
        <y>-170.88</y>
        <z>-525</z>
      </point>
      <point>
        <id>7</id>
        <specification>0</specification>
        <x>-5.81445</x>
        <y>-178.087</y>
        <z>-536</z>
      </point>
      <point>
        <id>8</id>
        <specification>0</specification>
        <x>-6.61523</x>
        <y>-170.079</y>
        <z>-546</z>
      </point>
    </time_series>
  </point_set>
</point_set_file>
