<?xml version="1.0" encoding="ISO-8859-1"?>
<point_set_file>
  <file_version>0.1</file_version>
  <point_set>
    <time_series>
      <time_series_id>0</time_series_id>
      <point>
        <id>0</id>
        <specification>0</specification>
        <x>-8.42383</x>
        <y>-113.677</y>
        <z>-302</z>
      </point>
      <point>
        <id>1</id>
        <specification>0</specification>
        <x>-40.6973</x>
        <y>-133.611</y>
        <z>-294</z>
      </point>
      <point>
        <id>2</id>
        <specification>0</specification>
        <x>42.834</x>
        <y>-125.068</y>
        <z>-310</z>
      </point>
    </time_series>
  </point_set>
</point_set_file>
