<?xml version="1.0" encoding="ISO-8859-1"?>
<point_set_file>
  <file_version>0.1</file_version>
  <point_set>
    <time_series>
      <time_series_id>0</time_series_id>
      <point>
        <id>0</id>
        <specification>0</specification>
        <x>42.1875</x>
        <y>98.5156</y>
        <z>25.6</z>
      </point>
      <point>
        <id>1</id>
        <specification>0</specification>
        <x>76.8203</x>
        <y>140.232</y>
        <z>-23.4</z>
      </point>
      <point>
        <id>2</id>
        <specification>0</specification>
        <x>-51.4785</x>
        <y>141.807</y>
        <z>-10.4</z>
      </point>
      <point>
        <id>3</id>
        <specification>0</specification>
        <x>12.2773</x>
        <y>158.336</y>
        <z>-10.4</z>
      </point>
      <point>
        <id>4</id>
        <specification>0</specification>
        <x>-5.82617</x>
        <y>166.994</y>
        <z>-23.4</z>
      </point>
      <point>
        <id>5</id>
        <specification>0</specification>
        <x>-8.97461</x>
        <y>144.168</y>
        <z>13.6</z>
      </point>
      <point>
        <id>6</id>
        <specification>0</specification>
        <x>-5.03906</x>
        <y>131.574</y>
        <z>39.6</z>
      </point>
      <point>
        <id>7</id>
        <specification>0</specification>
        <x>-7.40039</x>
        <y>134.723</y>
        <z>23.6</z>
      </point>
    </time_series>
  </point_set>
</point_set_file>
