<?xml version="1.0" encoding="ISO-8859-1"?>
<point_set_file>
  <file_version>0.1</file_version>
  <point_set>
    <time_series>
      <time_series_id>0</time_series_id>
      <point>
        <id>0</id>
        <specification>0</specification>
        <x>25.6602</x>
        <y>133.254</y>
        <z>-240.6</z>
      </point>
      <point>
        <id>1</id>
        <specification>0</specification>
        <x>15.4063</x>
        <y>143.508</y>
        <z>-240.6</z>
      </point>
      <point>
        <id>2</id>
        <specification>0</specification>
        <x>30.4453</x>
        <y>116.848</y>
        <z>-249.6</z>
      </point>
      <point>
        <id>3</id>
        <specification>0</specification>
        <x>20.875</x>
        <y>157.863</y>
        <z>-245.6</z>
      </point>
    </time_series>
  </point_set>
</point_set_file>
