<?xml version="1.0" encoding="ISO-8859-1"?>
<point_set_file>
  <file_version>0.1</file_version>
  <point_set>
    <time_series>
      <time_series_id>0</time_series_id>
      <point>
        <id>0</id>
        <specification>0</specification>
        <x>0.59375</x>
        <y>167.813</y>
        <z>-268.7</z>
      </point>
      <point>
        <id>1</id>
        <specification>0</specification>
        <x>-4.21094</x>
        <y>173.418</y>
        <z>-282.45</z>
      </point>
      <point>
        <id>2</id>
        <specification>0</specification>
        <x>-9.81641</x>
        <y>148.594</y>
        <z>-249.95</z>
      </point>
      <point>
        <id>3</id>
        <specification>0</specification>
        <x>7</x>
        <y>153.398</y>
        <z>-249.95</z>
      </point>
    </time_series>
  </point_set>
</point_set_file>
