<?xml version="1.0" encoding="ISO-8859-1"?>
<point_set_file>
  <file_version>0.1</file_version>
  <point_set>
    <time_series>
      <time_series_id>0</time_series_id>
      <point>
        <id>0</id>
        <specification>0</specification>
        <x>29.1797</x>
        <y>-149.645</y>
        <z>-247.5</z>
      </point>
      <point>
        <id>1</id>
        <specification>0</specification>
        <x>13.8672</x>
        <y>-195.582</y>
        <z>-313.5</z>
      </point>
      <point>
        <id>2</id>
        <specification>0</specification>
        <x>25.3516</x>
        <y>-119.02</y>
        <z>-285.5</z>
      </point>
    </time_series>
  </point_set>
</point_set_file>
