<?xml version="1.0" encoding="ISO-8859-1"?>
<point_set_file>
  <file_version>0.1</file_version>
  <point_set>
    <time_series>
      <time_series_id>0</time_series_id>
      <point>
        <id>0</id>
        <specification>0</specification>
        <x>-36.5313</x>
        <y>-152.736</y>
        <z>-307</z>
      </point>
      <point>
        <id>1</id>
        <specification>0</specification>
        <x>1.90625</x>
        <y>-138.674</y>
        <z>-308</z>
      </point>
      <point>
        <id>2</id>
        <specification>0</specification>
        <x>-2.78125</x>
        <y>-144.299</y>
        <z>-311</z>
      </point>
      <point>
        <id>3</id>
        <specification>0</specification>
        <x>45.0313</x>
        <y>-141.486</y>
        <z>-312</z>
      </point>
      <point>
        <id>4</id>
        <specification>0</specification>
        <x>-18.7188</x>
        <y>-238.049</y>
        <z>-362</z>
      </point>
    </time_series>
  </point_set>
</point_set_file>
