<?xml version="1.0" encoding="ISO-8859-1"?>
<point_set_file>
  <file_version>0.1</file_version>
  <point_set>
    <time_series>
      <time_series_id>0</time_series_id>
      <point>
        <id>0</id>
        <specification>0</specification>
        <x>-8.38477</x>
        <y>-142.375</y>
        <z>-265</z>
      </point>
      <point>
        <id>1</id>
        <specification>0</specification>
        <x>25.041</x>
        <y>-126.828</y>
        <z>-307</z>
      </point>
      <point>
        <id>2</id>
        <specification>0</specification>
        <x>25.8184</x>
        <y>-139.265</y>
        <z>-238</z>
      </point>
      <point>
        <id>3</id>
        <specification>0</specification>
        <x>-6.83008</x>
        <y>-133.047</y>
        <z>-273</z>
      </point>
      <point>
        <id>4</id>
        <specification>0</specification>
        <x>28.9277</x>
        <y>-108.949</y>
        <z>-273</z>
      </point>
      <point>
        <id>5</id>
        <specification>0</specification>
        <x>0.166016</x>
        <y>-148.594</y>
        <z>-258</z>
      </point>
      <point>
        <id>6</id>
        <specification>0</specification>
        <x>25.8184</x>
        <y>-129.16</y>
        <z>-272</z>
      </point>
    </time_series>
  </point_set>
</point_set_file>
