<?xml version="1.0" encoding="ISO-8859-1"?>
<point_set_file>
  <file_version>0.1</file_version>
  <point_set>
    <time_series>
      <time_series_id>0</time_series_id>
      <point>
        <id>0</id>
        <specification>0</specification>
        <x>44.4336</x>
        <y>-164.401</y>
        <z>-361.5</z>
      </point>
      <point>
        <id>1</id>
        <specification>0</specification>
        <x>49.3164</x>
        <y>-155.612</y>
        <z>-347.5</z>
      </point>
      <point>
        <id>2</id>
        <specification>0</specification>
        <x>37.5977</x>
        <y>-177.096</y>
        <z>-375.5</z>
      </point>
    </time_series>
  </point_set>
</point_set_file>
