<?xml version="1.0" encoding="ISO-8859-1"?>
<point_set_file>
  <file_version>0.1</file_version>
  <point_set>
    <time_series>
      <time_series_id>0</time_series_id>
      <point>
        <id>0</id>
        <specification>0</specification>
        <x>47.5801</x>
        <y>-125.068</y>
        <z>-307</z>
      </point>
      <point>
        <id>1</id>
        <specification>0</specification>
        <x>39.0371</x>
        <y>-139.306</y>
        <z>-308</z>
      </point>
    </time_series>
  </point_set>
</point_set_file>
