<?xml version="1.0" encoding="ISO-8859-1"?>
<point_set_file>
  <file_version>0.1</file_version>
  <point_set>
    <time_series>
      <time_series_id>0</time_series_id>
      <point>
        <id>0</id>
        <specification>0</specification>
        <x>31.992</x>
        <y>-159.268</y>
        <z>1378.42</z>
      </point>
      <point>
        <id>1</id>
        <specification>0</specification>
        <x>10.1643</x>
        <y>-162.431</y>
        <z>1383.44</z>
      </point>
      <point>
        <id>2</id>
        <specification>0</specification>
        <x>3.85938</x>
        <y>-154.666</y>
        <z>1384.4</z>
      </point>
    </time_series>
  </point_set>
</point_set_file>
