<?xml version="1.0" encoding="ISO-8859-1"?>
<point_set_file>
  <file_version>0.1</file_version>
  <point_set>
    <time_series>
      <time_series_id>0</time_series_id>
      <point>
        <id>0</id>
        <specification>0</specification>
        <x>-9.8827</x>
        <y>10.7814</y>
        <z>-132.5</z>
      </point>
      <point>
        <id>1</id>
        <specification>0</specification>
        <x>-8.08582</x>
        <y>7.18763</y>
        <z>-115</z>
      </point>
    </time_series>
  </point_set>
</point_set_file>
