<?xml version="1.0" encoding="ISO-8859-1"?>
<point_set_file>
  <file_version>0.1</file_version>
  <point_set>
    <time_series>
      <time_series_id>0</time_series_id>
      <point>
        <id>0</id>
        <specification>0</specification>
        <x>-75.6015</x>
        <y>-200.626</y>
        <z>-509.404</z>
      </point>
      <point>
        <id>1</id>
        <specification>0</specification>
        <x>-65.9077</x>
        <y>-169.438</y>
        <z>-528.429</z>
      </point>
      <point>
        <id>2</id>
        <specification>0</specification>
        <x>-61.9753</x>
        <y>-189.893</y>
        <z>-547.489</z>
      </point>
    </time_series>
  </point_set>
</point_set_file>
