<?xml version="1.0" encoding="ISO-8859-1"?>
<point_set_file>
  <file_version>0.1</file_version>
  <point_set>
    <time_series>
      <time_series_id>0</time_series_id>
      <point>
        <id>0</id>
        <specification>0</specification>
        <x>-14.9844</x>
        <y>-181.699</y>
        <z>-366</z>
      </point>
      <point>
        <id>1</id>
        <specification>0</specification>
        <x>-30.3906</x>
        <y>-177.168</y>
        <z>-363</z>
      </point>
      <point>
        <id>2</id>
        <specification>0</specification>
        <x>12.2031</x>
        <y>-139.106</y>
        <z>-264</z>
      </point>
      <point>
        <id>3</id>
        <specification>0</specification>
        <x>-19.5156</x>
        <y>-159.949</y>
        <z>-298</z>
      </point>
      <point>
        <id>4</id>
        <specification>0</specification>
        <x>13.1094</x>
        <y>-133.668</y>
        <z>-239</z>
      </point>
    </time_series>
  </point_set>
</point_set_file>
