<?xml version="1.0" encoding="ISO-8859-1"?>
<point_set_file>
  <file_version>0.1</file_version>
  <point_set>
    <time_series>
      <time_series_id>0</time_series_id>
      <point>
        <id>0</id>
        <specification>0</specification>
        <x>-2.8125</x>
        <y>23.2031</y>
        <z>-172.5</z>
      </point>
      <point>
        <id>1</id>
        <specification>0</specification>
        <x>-13.3594</x>
        <y>4.21875</y>
        <z>-137.5</z>
      </point>
      <point>
        <id>2</id>
        <specification>0</specification>
        <x>-11.9531</x>
        <y>-0.703125</y>
        <z>-102.5</z>
      </point>
      <point>
        <id>3</id>
        <specification>0</specification>
        <x>-0.703125</x>
        <y>12.6563</y>
        <z>-157.5</z>
      </point>
    </time_series>
  </point_set>
</point_set_file>
