<?xml version="1.0" encoding="ISO-8859-1"?>
<point_set_file>
  <file_version>0.1</file_version>
  <point_set>
    <time_series>
      <time_series_id>0</time_series_id>
      <point>
        <id>0</id>
        <specification>0</specification>
        <x>-14.5313</x>
        <y>-175.571</y>
        <z>-1</z>
      </point>
      <point>
        <id>1</id>
        <specification>0</specification>
        <x>-14.5313</x>
        <y>-168.071</y>
        <z>-3</z>
      </point>
      <point>
        <id>2</id>
        <specification>0</specification>
        <x>-11.7188</x>
        <y>-169.946</y>
        <z>-13</z>
      </point>
      <point>
        <id>3</id>
        <specification>0</specification>
        <x>-24.8438</x>
        <y>-164.321</y>
        <z>-20</z>
      </point>
      <point>
        <id>4</id>
        <specification>0</specification>
        <x>33.2813</x>
        <y>-158.696</y>
        <z>-41</z>
      </point>
      <point>
        <id>5</id>
        <specification>0</specification>
        <x>-10.7813</x>
        <y>-138.071</y>
        <z>-63</z>
      </point>
      <point>
        <id>6</id>
        <specification>0</specification>
        <x>7.96875</x>
        <y>-140.884</y>
        <z>-68</z>
      </point>
      <point>
        <id>7</id>
        <specification>0</specification>
        <x>57.6563</x>
        <y>-141.821</y>
        <z>-80</z>
      </point>
      <point>
        <id>8</id>
        <specification>0</specification>
        <x>-52.0313</x>
        <y>-144.634</y>
        <z>-81</z>
      </point>
      <point>
        <id>9</id>
        <specification>0</specification>
        <x>-52.0313</x>
        <y>-156.821</y>
        <z>-83</z>
      </point>
      <point>
        <id>10</id>
        <specification>0</specification>
        <x>-55.7813</x>
        <y>-139.009</y>
        <z>-88</z>
      </point>
      <point>
        <id>11</id>
        <specification>0</specification>
        <x>-52.9688</x>
        <y>-147.446</y>
        <z>-90</z>
      </point>
      <point>
        <id>12</id>
        <specification>0</specification>
        <x>-15.4688</x>
        <y>-130.571</y>
        <z>-96</z>
      </point>
      <point>
        <id>13</id>
        <specification>0</specification>
        <x>-11.7188</x>
        <y>-266.509</y>
        <z>-151</z>
      </point>
    </time_series>
  </point_set>
</point_set_file>
