<?xml version="1.0" encoding="ISO-8859-1"?>
<point_set_file>
  <file_version>0.1</file_version>
  <point_set>
    <time_series>
      <time_series_id>0</time_series_id>
      <point>
        <id>0</id>
        <specification>0</specification>
        <x>22.3047</x>
        <y>150.898</y>
        <z>-423.4</z>
      </point>
      <point>
        <id>1</id>
        <specification>0</specification>
        <x>-2.15625</x>
        <y>160.367</y>
        <z>-473.4</z>
      </point>
    </time_series>
  </point_set>
</point_set_file>
