<?xml version="1.0" encoding="ISO-8859-1"?>
<point_set_file>
  <file_version>0.1</file_version>
  <point_set>
    <time_series>
      <time_series_id>0</time_series_id>
      <point>
        <id>0</id>
        <specification>0</specification>
        <x>-9.69523</x>
        <y>15.0411</y>
        <z>-89.75</z>
      </point>
      <point>
        <id>1</id>
        <specification>0</specification>
        <x>13.3087</x>
        <y>33.6212</y>
        <z>-104.75</z>
      </point>
    </time_series>
  </point_set>
</point_set_file>
