<?xml version="1.0" encoding="ISO-8859-1"?>
<point_set_file>
  <file_version>0.1</file_version>
  <point_set>
    <time_series>
      <time_series_id>0</time_series_id>
      <point>
        <id>0</id>
        <specification>0</specification>
        <x>-4.21875</x>
        <y>-134.321</y>
        <z>-87</z>
      </point>
      <point>
        <id>1</id>
        <specification>0</specification>
        <x>-0.46875</x>
        <y>-139.009</y>
        <z>-63</z>
      </point>
      <point>
        <id>2</id>
        <specification>0</specification>
        <x>26.7188</x>
        <y>-145.571</y>
        <z>-45</z>
      </point>
      <point>
        <id>3</id>
        <specification>0</specification>
        <x>-16.4063</x>
        <y>-167.134</y>
        <z>-13</z>
      </point>
      <point>
        <id>4</id>
        <specification>0</specification>
        <x>60.4688</x>
        <y>-145.571</y>
        <z>-87</z>
      </point>
      <point>
        <id>5</id>
        <specification>0</specification>
        <x>-58.5938</x>
        <y>-225.259</y>
        <z>-155</z>
      </point>
      <point>
        <id>6</id>
        <specification>0</specification>
        <x>-52.0313</x>
        <y>-150.259</y>
        <z>-87</z>
      </point>
      <point>
        <id>7</id>
        <specification>0</specification>
        <x>35.1563</x>
        <y>-160.571</y>
        <z>-45</z>
      </point>
      <point>
        <id>8</id>
        <specification>0</specification>
        <x>78.2813</x>
        <y>-260.884</y>
        <z>-174</z>
      </point>
      <point>
        <id>9</id>
        <specification>0</specification>
        <x>-14.5313</x>
        <y>-267.446</y>
        <z>-154</z>
      </point>
    </time_series>
  </point_set>
</point_set_file>
