<?xml version="1.0" encoding="ISO-8859-1"?>
<point_set_file>
  <file_version>0.1</file_version>
  <point_set>
    <time_series>
      <time_series_id>0</time_series_id>
      <point>
        <id>0</id>
        <specification>0</specification>
        <x>34.332</x>
        <y>185.965</y>
        <z>-200.9</z>
      </point>
      <point>
        <id>1</id>
        <specification>0</specification>
        <x>44.5859</x>
        <y>193.484</y>
        <z>-214.9</z>
      </point>
    </time_series>
  </point_set>
</point_set_file>
