<?xml version="1.0" encoding="ISO-8859-1"?>
<point_set_file>
  <file_version>0.1</file_version>
  <point_set>
    <time_series>
      <time_series_id>0</time_series_id>
      <point>
        <id>0</id>
        <specification>0</specification>
        <x>-15.3875</x>
        <y>26.25</y>
        <z>-611</z>
      </point>
      <point>
        <id>1</id>
        <specification>0</specification>
        <x>36.175</x>
        <y>-4.6875</y>
        <z>-573</z>
      </point>
      <point>
        <id>2</id>
        <specification>0</specification>
        <x>53.9875</x>
        <y>10.3125</y>
        <z>-571</z>
      </point>
      <point>
        <id>3</id>
        <specification>0</specification>
        <x>55.8625</x>
        <y>-2.8125</y>
        <z>-561</z>
      </point>
      <point>
        <id>4</id>
        <specification>0</specification>
        <x>-9.7625</x>
        <y>-40.3125</y>
        <z>-344</z>
      </point>
    </time_series>
  </point_set>
</point_set_file>
