<?xml version="1.0" encoding="ISO-8859-1"?>
<point_set_file>
  <file_version>0.1</file_version>
  <point_set>
    <time_series>
      <time_series_id>0</time_series_id>
      <point>
        <id>0</id>
        <specification>0</specification>
        <x>84.1621</x>
        <y>-221.118</y>
        <z>-626</z>
      </point>
      <point>
        <id>1</id>
        <specification>0</specification>
        <x>62.7637</x>
        <y>-151.086</y>
        <z>-579</z>
      </point>
      <point>
        <id>2</id>
        <specification>0</specification>
        <x>0.513672</x>
        <y>-194.856</y>
        <z>-299</z>
      </point>
      <point>
        <id>3</id>
        <specification>0</specification>
        <x>-20.8848</x>
        <y>-201.665</y>
        <z>-299</z>
      </point>
      <point>
        <id>4</id>
        <specification>0</specification>
        <x>-53.9551</x>
        <y>-213.336</y>
        <z>-323</z>
      </point>
      <point>
        <id>5</id>
        <specification>0</specification>
        <x>-39.3652</x>
        <y>-190.965</y>
        <z>-326</z>
      </point>
      <point>
        <id>6</id>
        <specification>0</specification>
        <x>-63.6816</x>
        <y>-222.09</y>
        <z>-337</z>
      </point>
    </time_series>
  </point_set>
</point_set_file>
