<?xml version="1.0" encoding="ISO-8859-1"?>
<point_set_file>
  <file_version>0.1</file_version>
  <point_set>
    <time_series>
      <time_series_id>0</time_series_id>
      <point>
        <id>0</id>
        <specification>0</specification>
        <x>-44.4336</x>
        <y>-208.111</y>
        <z>588</z>
      </point>
      <point>
        <id>1</id>
        <specification>0</specification>
        <x>-21.9727</x>
        <y>-123.15</y>
        <z>834</z>
      </point>
      <point>
        <id>2</id>
        <specification>0</specification>
        <x>44.4336</x>
        <y>-116.315</y>
        <z>910</z>
      </point>
      <point>
        <id>3</id>
        <specification>0</specification>
        <x>15.1367</x>
        <y>-163.19</y>
        <z>887</z>
      </point>
      <point>
        <id>4</id>
        <specification>0</specification>
        <x>16.1133</x>
        <y>-173.932</y>
        <z>822</z>
      </point>
      <point>
        <id>5</id>
        <specification>0</specification>
        <x>-22.9492</x>
        <y>-149.518</y>
        <z>835</z>
      </point>
      <point>
        <id>6</id>
        <specification>0</specification>
        <x>-9.27734</x>
        <y>-153.424</y>
        <z>818</z>
      </point>
    </time_series>
  </point_set>
</point_set_file>
