<?xml version="1.0" encoding="ISO-8859-1"?>
<point_set_file>
  <file_version>0.1</file_version>
  <point_set>
    <time_series>
      <time_series_id>0</time_series_id>
      <point>
        <id>0</id>
        <specification>0</specification>
        <x>10.1094</x>
        <y>-162.478</y>
        <z>1383.4</z>
      </point>
      <point>
        <id>1</id>
        <specification>0</specification>
        <x>31.9844</x>
        <y>-159.353</y>
        <z>1378.4</z>
      </point>
    </time_series>
  </point_set>
</point_set_file>
