<?xml version="1.0" encoding="ISO-8859-1"?>
<point_set_file>
  <file_version>0.1</file_version>
  <point_set>
    <time_series>
      <time_series_id>0</time_series_id>
      <point>
        <id>0</id>
        <specification>0</specification>
        <x>29.1055</x>
        <y>138.9</y>
        <z>-328.7</z>
      </point>
      <point>
        <id>1</id>
        <specification>0</specification>
        <x>27.576</x>
        <y>141.395</y>
        <z>-324.674</z>
      </point>
    </time_series>
  </point_set>
</point_set_file>
