<?xml version="1.0" encoding="ISO-8859-1"?>
<point_set_file>
  <file_version>0.1</file_version>
  <point_set>
    <time_series>
      <time_series_id>0</time_series_id>
      <point>
        <id>0</id>
        <specification>0</specification>
        <x>51.7188</x>
        <y>-185.229</y>
        <z>-618.5</z>
      </point>
      <point>
        <id>1</id>
        <specification>0</specification>
        <x>35.7813</x>
        <y>-174.916</y>
        <z>-457.5</z>
      </point>
    </time_series>
  </point_set>
</point_set_file>
