<?xml version="1.0" encoding="ISO-8859-1"?>
<point_set_file>
  <file_version>0.1</file_version>
  <point_set>
    <time_series>
      <time_series_id>0</time_series_id>
      <point>
        <id>0</id>
        <specification>0</specification>
        <x>2.19336</x>
        <y>-178.888</y>
        <z>-542</z>
      </point>
      <point>
        <id>1</id>
        <specification>0</specification>
        <x>-5.01367</x>
        <y>-172.482</y>
        <z>-522</z>
      </point>
      <point>
        <id>2</id>
        <specification>0</specification>
        <x>42.2324</x>
        <y>-162.872</y>
        <z>-516</z>
      </point>
    </time_series>
  </point_set>
</point_set_file>
