<?xml version="1.0" encoding="ISO-8859-1"?>
<point_set_file>
  <file_version>0.1</file_version>
  <point_set>
    <time_series>
      <time_series_id>0</time_series_id>
      <point>
        <id>0</id>
        <specification>0</specification>
        <x>-49.1063</x>
        <y>42.3827</y>
        <z>-137.25</z>
      </point>
      <point>
        <id>1</id>
        <specification>0</specification>
        <x>-22.829</x>
        <y>61.8788</y>
        <z>-167.25</z>
      </point>
      <point>
        <id>2</id>
        <specification>0</specification>
        <x>-50.8016</x>
        <y>50.0116</y>
        <z>-174.25</z>
      </point>
    </time_series>
  </point_set>
</point_set_file>
