<?xml version="1.0" encoding="ISO-8859-1"?>
<point_set_file>
  <file_version>0.1</file_version>
  <point_set>
    <time_series>
      <time_series_id>0</time_series_id>
      <point>
        <id>0</id>
        <specification>0</specification>
        <x>42.6563</x>
        <y>-169.844</y>
        <z>677</z>
      </point>
      <point>
        <id>1</id>
        <specification>0</specification>
        <x>22.9688</x>
        <y>-190.469</y>
        <z>719</z>
      </point>
    </time_series>
  </point_set>
</point_set_file>
