<?xml version="1.0" encoding="ISO-8859-1"?>
<point_set_file>
  <file_version>0.1</file_version>
  <point_set>
    <time_series>
      <time_series_id>0</time_series_id>
      <point>
        <id>0</id>
        <specification>0</specification>
        <x>-21.7813</x>
        <y>144.051</y>
        <z>-216.6</z>
      </point>
      <point>
        <id>1</id>
        <specification>0</specification>
        <x>-22.5039</x>
        <y>162.117</y>
        <z>-229.6</z>
      </point>
      <point>
        <id>2</id>
        <specification>0</specification>
        <x>-26.8398</x>
        <y>163.563</y>
        <z>-242.6</z>
      </point>
    </time_series>
  </point_set>
</point_set_file>
