<?xml version="1.0" encoding="ISO-8859-1"?>
<point_set_file>
  <file_version>0.1</file_version>
  <point_set>
    <time_series>
      <time_series_id>0</time_series_id>
      <point>
        <id>0</id>
        <specification>0</specification>
        <x>-1.36328</x>
        <y>180.191</y>
        <z>-230.371</z>
      </point>
      <point>
        <id>1</id>
        <specification>0</specification>
        <x>-9.84766</x>
        <y>179.484</y>
        <z>-204.37</z>
      </point>
    </time_series>
  </point_set>
</point_set_file>
