<?xml version="1.0" encoding="ISO-8859-1"?>
<point_set_file>
  <file_version>0.1</file_version>
  <point_set>
    <time_series>
      <time_series_id>0</time_series_id>
      <point>
        <id>0</id>
        <specification>0</specification>
        <x>35.5078</x>
        <y>-145.593</y>
        <z>-314.6</z>
      </point>
      <point>
        <id>1</id>
        <specification>0</specification>
        <x>22.1484</x>
        <y>-144.187</y>
        <z>-318.6</z>
      </point>
    </time_series>
  </point_set>
</point_set_file>
