<?xml version="1.0" encoding="ISO-8859-1"?>
<point_set_file>
  <file_version>0.1</file_version>
  <point_set>
    <time_series>
      <time_series_id>0</time_series_id>
      <point>
        <id>0</id>
        <specification>0</specification>
        <x>-12.4707</x>
        <y>-114.434</y>
        <z>-64.2</z>
      </point>
      <point>
        <id>1</id>
        <specification>0</specification>
        <x>-15.7363</x>
        <y>-138.11</y>
        <z>16.8</z>
      </point>
      <point>
        <id>2</id>
        <specification>0</specification>
        <x>-7.57227</x>
        <y>-137.293</y>
        <z>35.8</z>
      </point>
      <point>
        <id>3</id>
        <specification>0</specification>
        <x>-42.6777</x>
        <y>-132.395</y>
        <z>-53.2</z>
      </point>
      <point>
        <id>4</id>
        <specification>0</specification>
        <x>-55.7402</x>
        <y>-125.047</y>
        <z>-82.2</z>
      </point>
      <point>
        <id>5</id>
        <specification>0</specification>
        <x>19.3691</x>
        <y>-130.762</y>
        <z>-31.2</z>
      </point>
    </time_series>
  </point_set>
</point_set_file>
