<?xml version="1.0" encoding="ISO-8859-1"?>
<point_set_file>
  <file_version>0.1</file_version>
  <point_set>
    <time_series>
      <time_series_id>0</time_series_id>
      <point>
        <id>0</id>
        <specification>0</specification>
        <x>-6.95117</x>
        <y>-104.32</y>
        <z>-129</z>
      </point>
      <point>
        <id>1</id>
        <specification>0</specification>
        <x>1.29102</x>
        <y>-111.738</y>
        <z>-134</z>
      </point>
      <point>
        <id>2</id>
        <specification>0</specification>
        <x>-29.2051</x>
        <y>-119.98</y>
        <z>-139</z>
      </point>
      <point>
        <id>3</id>
        <specification>0</specification>
        <x>9.5332</x>
        <y>-114.211</y>
        <z>-142</z>
      </point>
    </time_series>
  </point_set>
</point_set_file>
