<?xml version="1.0" encoding="ISO-8859-1"?>
<point_set_file>
  <file_version>0.1</file_version>
  <point_set>
    <time_series>
      <time_series_id>0</time_series_id>
      <point>
        <id>0</id>
        <specification>0</specification>
        <x>-40.0688</x>
        <y>21.875</y>
        <z>-117.5</z>
      </point>
      <point>
        <id>1</id>
        <specification>0</specification>
        <x>-60.3813</x>
        <y>12.5</y>
        <z>-157.5</z>
      </point>
      <point>
        <id>2</id>
        <specification>0</specification>
        <x>-14.2875</x>
        <y>19.5313</y>
        <z>-157.5</z>
      </point>
      <point>
        <id>3</id>
        <specification>0</specification>
        <x>-32.2563</x>
        <y>28.125</y>
        <z>-187.5</z>
      </point>
      <point>
        <id>4</id>
        <specification>0</specification>
        <x>48.9937</x>
        <y>25</y>
        <z>-161.25</z>
      </point>
      <point>
        <id>5</id>
        <specification>0</specification>
        <x>-68.975</x>
        <y>12.5</y>
        <z>-187.5</z>
      </point>
      <point>
        <id>6</id>
        <specification>0</specification>
        <x>1.33749</x>
        <y>15.625</y>
        <z>-128.75</z>
      </point>
      <point>
        <id>7</id>
        <specification>0</specification>
        <x>-32.2563</x>
        <y>2.34375</y>
        <z>-132.5</z>
      </point>
    </time_series>
  </point_set>
</point_set_file>
