<?xml version="1.0" encoding="ISO-8859-1"?>
<point_set_file>
  <file_version>0.1</file_version>
  <point_set>
    <time_series>
      <time_series_id>0</time_series_id>
      <point>
        <id>0</id>
        <specification>0</specification>
        <x>0.03125</x>
        <y>-138.674</y>
        <z>-307</z>
      </point>
      <point>
        <id>1</id>
        <specification>0</specification>
        <x>-30.9063</x>
        <y>-148.049</y>
        <z>-320</z>
      </point>
      <point>
        <id>2</id>
        <specification>0</specification>
        <x>-42.1563</x>
        <y>-150.861</y>
        <z>-317</z>
      </point>
      <point>
        <id>3</id>
        <specification>0</specification>
        <x>47.8438</x>
        <y>-141.486</y>
        <z>-311</z>
      </point>
      <point>
        <id>4</id>
        <specification>0</specification>
        <x>-14.9688</x>
        <y>-241.799</y>
        <z>-355</z>
      </point>
      <point>
        <id>5</id>
        <specification>0</specification>
        <x>64.7188</x>
        <y>-237.111</y>
        <z>-370</z>
      </point>
      <point>
        <id>6</id>
        <specification>0</specification>
        <x>10.3438</x>
        <y>-173.361</y>
        <z>-368</z>
      </point>
    </time_series>
  </point_set>
</point_set_file>
