<?xml version="1.0" encoding="ISO-8859-1"?>
<point_set_file>
  <file_version>0.1</file_version>
  <point_set>
    <time_series>
      <time_series_id>0</time_series_id>
      <point>
        <id>0</id>
        <specification>0</specification>
        <x>-9.43359</x>
        <y>-131.682</y>
        <z>167.5</z>
      </point>
      <point>
        <id>1</id>
        <specification>0</specification>
        <x>-18.418</x>
        <y>-145.159</y>
        <z>194.5</z>
      </point>
      <point>
        <id>2</id>
        <specification>0</specification>
        <x>44.4727</x>
        <y>-122.698</y>
        <z>161.5</z>
      </point>
      <point>
        <id>3</id>
        <specification>0</specification>
        <x>9.43359</x>
        <y>-127.19</y>
        <z>158.5</z>
      </point>
    </time_series>
  </point_set>
</point_set_file>
