<?xml version="1.0" encoding="ISO-8859-1"?>
<point_set_file>
  <file_version>0.1</file_version>
  <point_set>
    <time_series>
      <time_series_id>0</time_series_id>
      <point>
        <id>0</id>
        <specification>0</specification>
        <x>-44.2324</x>
        <y>-158.176</y>
        <z>-149.5</z>
      </point>
      <point>
        <id>1</id>
        <specification>0</specification>
        <x>-57.5332</x>
        <y>-159.95</y>
        <z>-160.5</z>
      </point>
      <point>
        <id>2</id>
        <specification>0</specification>
        <x>-57.5332</x>
        <y>-166.157</y>
        <z>-172.5</z>
      </point>
      <point>
        <id>3</id>
        <specification>0</specification>
        <x>-53.0996</x>
        <y>-163.497</y>
        <z>-179.5</z>
      </point>
    </time_series>
  </point_set>
</point_set_file>
