<?xml version="1.0" encoding="ISO-8859-1"?>
<point_set_file>
  <file_version>0.1</file_version>
  <point_set>
    <time_series>
      <time_series_id>0</time_series_id>
      <point>
        <id>0</id>
        <specification>0</specification>
        <x>10.9297</x>
        <y>-136.522</y>
        <z>1197.5</z>
      </point>
      <point>
        <id>1</id>
        <specification>0</specification>
        <x>0.976563</x>
        <y>-112.787</y>
        <z>1019.5</z>
      </point>
      <point>
        <id>2</id>
        <specification>0</specification>
        <x>-5.91406</x>
        <y>-119.678</y>
        <z>991.5</z>
      </point>
    </time_series>
  </point_set>
</point_set_file>
