<?xml version="1.0" encoding="ISO-8859-1"?>
<point_set_file>
  <file_version>0.1</file_version>
  <point_set>
    <time_series>
      <time_series_id>0</time_series_id>
      <point>
        <id>0</id>
        <specification>0</specification>
        <x>9.83594</x>
        <y>213.637</y>
        <z>-522.55</z>
      </point>
      <point>
        <id>1</id>
        <specification>0</specification>
        <x>-63.3086</x>
        <y>130.238</y>
        <z>-496.3</z>
      </point>
      <point>
        <id>2</id>
        <specification>0</specification>
        <x>-1.10156</x>
        <y>141.176</y>
        <z>-286.3</z>
      </point>
    </time_series>
  </point_set>
</point_set_file>
