<?xml version="1.0" encoding="ISO-8859-1"?>
<point_set_file>
  <file_version>0.1</file_version>
  <point_set>
    <time_series>
      <time_series_id>0</time_series_id>
      <point>
        <id>0</id>
        <specification>0</specification>
        <x>-52.8398</x>
        <y>119.473</y>
        <z>853.3</z>
      </point>
      <point>
        <id>1</id>
        <specification>0</specification>
        <x>-38.4844</x>
        <y>138.613</y>
        <z>783.3</z>
      </point>
      <point>
        <id>2</id>
        <specification>0</specification>
        <x>-30.8281</x>
        <y>143.398</y>
        <z>776.3</z>
      </point>
      <point>
        <id>3</id>
        <specification>0</specification>
        <x>-42.3125</x>
        <y>138.613</y>
        <z>768.3</z>
      </point>
    </time_series>
  </point_set>
</point_set_file>
