<?xml version="1.0" encoding="ISO-8859-1"?>
<point_set_file>
  <file_version>0.1</file_version>
  <point_set>
    <time_series>
      <time_series_id>0</time_series_id>
      <point>
        <id>0</id>
        <specification>0</specification>
        <x>-6.83984</x>
        <y>-107.065</y>
        <z>-280</z>
      </point>
      <point>
        <id>1</id>
        <specification>0</specification>
        <x>-2.29297</x>
        <y>-112.37</y>
        <z>-283</z>
      </point>
    </time_series>
  </point_set>
</point_set_file>
