<?xml version="1.0" encoding="ISO-8859-1"?>
<point_set_file>
  <file_version>0.1</file_version>
  <point_set>
    <time_series>
      <time_series_id>0</time_series_id>
      <point>
        <id>0</id>
        <specification>0</specification>
        <x>-0.617188</x>
        <y>121.148</y>
        <z>-232.6</z>
      </point>
      <point>
        <id>1</id>
        <specification>0</specification>
        <x>8.52344</x>
        <y>108.961</y>
        <z>-238.6</z>
      </point>
      <point>
        <id>2</id>
        <specification>0</specification>
        <x>3.95313</x>
        <y>107.438</y>
        <z>-251.6</z>
      </point>
    </time_series>
  </point_set>
</point_set_file>
