<?xml version="1.0" encoding="ISO-8859-1"?>
<point_set_file>
  <file_version>0.1</file_version>
  <point_set>
    <time_series>
      <time_series_id>0</time_series_id>
      <point>
        <id>0</id>
        <specification>0</specification>
        <x>-15.1563</x>
        <y>-135.404</y>
        <z>41.9</z>
      </point>
      <point>
        <id>1</id>
        <specification>0</specification>
        <x>-6.71875</x>
        <y>-134.466</y>
        <z>27.9</z>
      </point>
      <point>
        <id>2</id>
        <specification>0</specification>
        <x>-51.7188</x>
        <y>-150.404</y>
        <z>-71.1</z>
      </point>
    </time_series>
  </point_set>
</point_set_file>
